(use-modules (guix packages)
             (guix licenses)
             (guix git-download)
             (guix build-system cmake)
             (guix build-system trivial)
             (guix build-system gnu)
             (gnu packages)
             (gnu packages docker)
             (gnu packages xorg)
             (gnu packages cmake)
             (gnu packages gdb)
             (gnu packages pkg-config)
             (gnu packages electronics)
             (gnu packages guile))

(package
  (name "Bachelorarbeit")
  (version "0.0")
  (source #f)
  (build-system cmake-build-system)
  (inputs
   `(("pulseview" ,pulseview)
     ("docker-cli" ,docker-cli)
     ("sigrok-cli" ,sigrok-cli)
     ("pkg-config" ,pkg-config)
     ("libsigrok" ,libsigrok)
     ("cmake" ,cmake)
     ("xhost" ,xhost)
     ("gdb", gdb)
     ))
  (synopsis "")
  (description "")
  (home-page "")
  (license gpl3+))
