(use-modules (guix packages)
             (guix licenses)
             (guix git-download)
             (guix build-system cmake)
             (guix build-system trivial)
             (guix build-system gnu)
             (gnu packages)
             (gnu packages docker)
             (gnu packages python)
             (gnu packages python-web)
             (gnu packages python-xyz)
             (gnu packages glib)
             (gnu packages xorg)
             (gnu packages cmake)
             (gnu packages gdb)
             (gnu packages pkg-config)
             (gnu packages electronics)
             (gnu packages guile))

(package
  (name "Bachelorarbeit")
  (version "0.0")
  (source #f)
  (build-system cmake-build-system)
  (inputs
   `(("pulseview" ,pulseview)
     ("docker-cli" ,docker-cli)
     ("sigrok-cli" ,sigrok-cli)
     ("pkg-config" ,pkg-config)
     ("libsigrok" ,libsigrok)
     ("cmake" ,cmake)
     ("glib" ,glib)
     ("xhost" ,xhost)
     ("gdb" ,gdb)
     ("python" ,python)
     ("python-flask-restful" ,python-flask-restful)
     ("python-dbus" ,python-dbus)
     ))
  (synopsis "")
  (description "")
  (home-page "")
  (license gpl3+))
