#ifndef TRANSMITTER_H
#define TRANSMITTER_H

#define TRANSMITTER_WARMUP_TRANSFER_PULSES 40

#define TRANSMITTER_WARMUP_HIGH_LENGTH 200
#define TRANSMITTER_WARMUP_LOW_LENGTH 100
#define TRANSMITTER_WARMUP_PULSE_INTERVAL 20

#define TRANSMITTER_SYNC_LENGTH TRANSMITTER_WARMUP_HIGH_LENGTH*200

#define TRANSMITTER_SYNC_LENGTH_TOLERANCE 1.04

/* #define TRANSMITTER_TRANSFER_REPEAT 40 */
/* #define TRANSMITTER_HIGH_LENGTH 400 */
/* #define TRANSMITTER_LOW_LENGTH 200 */
/* #define TRANSMITTER_PULSE_INTERVAL 50 */


#endif /* TRANSMITTER_H */
