#ifndef TRANSMITTER_H
#define TRANSMITTER_H

#define TRANSMITTER_WARMUP_TRANSFER_PULSES 1500

#define TRANSMITTER_WARMUP_HIGH_LENGTH 400
#define TRANSMITTER_WARMUP_LOW_LENGTH 200

#define TRANSMITTER_SYNC_PULSES 5
#define TRANSMITTER_SYNC_LENGTH TRANSMITTER_WARMUP_HIGH_LENGTH*2
#define TRANSMITTER_SYNC_LENGTH_TOLERANCE 1.25

#endif /* TRANSMITTER_H */
