#ifndef TYPES_H
#define TYPES_H

#include <time.h>
#include <sys/time.h>
#include <glib.h>

typedef enum match {
  MATCH_FALLING = 1,
  MATCH_RISING = 2,
} match_t;

// structure to represent trace data that is generated by the preprocess thread
// on the raw sigrok data from the logic analyzer
typedef struct trace {
  guint8 channel; // channel for which the state is recorded
  char state;
  guint64 timestamp_ns; // timestamp in nanoseconds
} trace_t;

#endif /* TYPES_H */
